version: '3'
services:
  app:
    image: jwt:1.0
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_PASSWORD=${SENHA_DB}
      - TOKEN=${TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SENHA_DB}
    ports:
      - "3306:3306"