version: '3'
services:
  app:
    image: jwt:1.0
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"