version: '3'
services:
  app:
    image: guirodg/jwt
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_PASSWORD=${SENHA_DB}
      - TOKEN=${TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy  
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SENHA_DB}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3